#!/bin/zsh
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
GREEN='\033[0;32m'
NC='\033[0m' # No Color
for i in ./values/*;do
    echo -n > $i
done
cp $DIR/.backup $DIR/contact.vcf
echo -e "${GREEN}Reset successful, returning to menu..${NC}"
sleep 1
$DIR/functions/openMenu
